### read investment by id
GET http://localhost:8080/investment/12

### create investment
POST http://localhost:8080/investment
Content-Type: application/json

{
  "purchasePrice": 1200.0,
  "purchaseDate": "2023-02-19",
  "sellingPrice": 0,
  "sellingDate": "2023-03-20",
  "possessionStatus": 1,
  "additionalInfo": "test",
  "portfolioId": 4,
  "legoSetId": 1
}


### update investment
PUT http://localhost:8080/investment/5
Content-Type: application/json

{
  "id": 5,
  "purchasePrice": 1200.5,
  "purchaseDate": "2023-02-19",
  "sellingPrice": 1550,
  "sellingDate": "2023-04-29",
  "possessionStatus": -1,
  "additionalInfo": null,
  "portfolioId": 1,
  "legoSetId": 2
}

### delete investment
DELETE http://localhost:8080/investment/5


### get all investments by portfolio id
GET http://localhost:8080/investment/all/1

### show all profits info for single investment
GET http://localhost:8080/investment/4/profit