GET http://localhost:8080/investment/12

### create
POST http://localhost:8080/investment
Content-Type: application/json

{
  "purchasePrice": 1200.0,
  "purchaseDate": "2023-02-19",
  "sellingPrice": 0,
  "sellingDate": "2023-03-20",
  "possessionStatus": 1,
  "additionalInfo": "test",
  "portfolioId": 3,
  "legoSetId": 4
}


### update
PUT http://localhost:8080/investment/12
Content-Type: application/json

{
  "id": 12,
  "purchasePrice": 1200.0,
  "purchaseDate": "2024-02-19",
  "sellingPrice": 0,
  "sellingDate": null,
  "possessionStatus": 1,
  "additionalInfo": null,
  "portfolioId": 6,
  "legoSetId": 6
}

###
DELETE http://localhost:8080/investment/7


### get all by portfolio id
GET http://localhost:8080/investment/all/8

### show all profits info
GET http://localhost:8080/investment/3/profit