GET http://localhost:8080/legoSet/5

###
POST http://localhost:8080/legoSet
Content-Type: application/json

{
  "legoSetNumber": 42110,
  "legoSetName": "Land Rover Defender",
  "series": "Technic",
  "releaseYear": 2019,
  "amountOfElements": 2573,
  "amountOfMinifigures": 0,
  "originalPrice": 949.99,
  "lowestCurrentPrice": 908.00
}


###
PUT http://localhost:8080/legoSet/7
Content-Type: application/json

{
  "id": 7,
  "legoSetNumber": 31097,
  "legoSetName": "Sklep zoologiczny i kawiarenka",
  "series": "Creator 3w1",
  "releaseYear": 2019,
  "amountOfElements": 969,
  "amountOfMinifigures": 3,
  "originalPrice": 329.99,
  "lowestCurrentPrice": null
}


###
DELETE http://localhost:8080/legoSet/7

###
GET http://localhost:8080/legoSet/all


### update price of one set
PUT http://localhost:8080/legoSet/price/2

### update price of all sets
PUT http://localhost:8080/legoSet/price/all

### update price of all sets in portfolio
PUT http://localhost:8080/legoSet/price/all/5