GET http://localhost:8080/portfolio/2

###
POST http://localhost:8080/portfolio
Content-Type: application/json

{
  "name": "portfel5",
  "description": "testowy portfel5",
  "user": {
    "id": 2
  }
}



###
PUT http://localhost:8080/portfolio/3
Content-Type: application/json

{
  "id": 3,
  "name": "portfel11",
  "description": "testowy portfel",
  "user": {
    "id": 1,
    "login": "nowyLogin",
    "password": "noweHasło",
    "email": "nowymail@onet.pl",
    "firstName": "nowy",
    "lastName": "ziomek"
  }
}


###
DELETE http://localhost:8080/portfolio/4


###
GET http://localhost:8080/portfolio/all/2