###
GET http://localhost:8080/user/2

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "ab",
  "password": "blablabla",
  "email": "niepoprawnyMail.xd",
  "firstName": "walidator",
  "lastName": "walidacyjny"
}


### edycja użytkownika
PUT http://localhost:8080/user/2
Content-Type: application/json

{
  "id": 2,
  "login": "no",
  "password": "noweHasło",
  "email": "mail@onet.pl",
  "firstName": "nowy",
  "lastName": "ziomek"
}


### usuwanie użytkownika
DELETE http://localhost:8080/user/3