GET http://localhost:8080/user/2

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "test1",
  "password": "testoweHasło1",
  "email": "testowyMail1@mail.eu",
  "firstName": "Testowy1",
  "lastName": "Ktoś1"
}


###
PUT http://localhost:8080/user/2
Content-Type: application/json

{
  "id": 2,
  "login": "nowyLogin",
  "password": "noweHasło",
  "email": "nowymail@onet.pl",
  "firstName": "nowy",
  "lastName": "ziomek"
}


###
DELETE http://localhost:8080/user/3